server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tickets?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: <your username>
    password: <your password>
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate.format_sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: your@gmail.com
    password: <16-digit app password>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

notification:
  base-url: http://localhost:8080
  contacts:
    user: user@x.com
    manager: manager@x.com
    admin: admin@x.com
  send:
    on-create: true
    on-approve: true
    on-reject: true
    on-resolve: true


storage:
  upload-dir: uploads
