server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tickets?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate.format_sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: yzq2236516175@gmail.com
    password: dbva zmbc wwov towg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



storage:
  upload-dir: uploads   # 相对项目根目录，会自动创建
