spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tickets?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port: 8081
